services:
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    networks:
      - default

  webapp:
    build: '.'
    restart: unless-stopped
    links:
      - postgres:postgres
    ports:
      - '9095:9095'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/
      - GATEWAY=${GATEWAY}
      - MIKROTIK_USER=${MIKROTIK_USER}
      - MIKROTIK_PASSWORD=${MIKROTIK_PASSWORD}
    networks:
      - default

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  monitoring:
    driver: bridge
    name: platform_admin_backend_monitoring
    external: false