version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
#    ports:
#      - '5432:5432'
  web:
    build: .
    restart: always
    links:
      - 'postgres:postgres'
    ports:
      - '8080:8080'
    environment:
      - MIKROTIK_PASSWORD=
      - MIKROTIK_USER=
      - GATEWAY=

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450