services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  web:
    build: .
    links:
      - 'db:postgres'
    ports:
      - '8080:8080'
    environment:
      - MIKROTIK_PASSWORD=
      - MIKROTIK_USER=
      - GATEWAY=